from typing import Final

STANDARD_CAREERS: Final[list[str]] = [
    "Software Engineer",
    "Data Scientist",
    "Product Manager",
    "UX Designer",
    "Marketing Specialist",
    "Finance Analyst",
    "HR Specialist",
    "Operations Manager",
    "Sales Executive",
    "Customer Success Manager",
    "Cybersecurity Analyst",
    "DevOps Engineer",
    "Business Analyst",
    "Project Manager",
    "Research Scientist",
    "Content Strategist",
    "Teacher",
    "Healthcare Administrator",
    "Architect",
    "Other",
]

CAREER_LABEL_COLUMNS: Final[tuple[str, ...]] = (
    "career",
    "career_label",
    "job_title",
    "profession",
    "role",
    "target",
    "label",
    "career_name",
    "occupation",
)

TEXT_COLUMNS: Final[tuple[str, ...]] = (
    "description",
    "summary",
    "details",
    "skills",
    "experience",
    "job_description",
    "requirements",
    "notes",
)

CAREER_ALIASES: Final[dict[str, str]] = {
    "software engineer": "Software Engineer",
    "software developer": "Software Engineer",
    "developer": "Software Engineer",
    "data scientist": "Data Scientist",
    "machine learning engineer": "Data Scientist",
    "ml engineer": "Data Scientist",
    "product manager": "Product Manager",
    "pm": "Product Manager",
    "ux designer": "UX Designer",
    "ui ux designer": "UX Designer",
    "marketing specialist": "Marketing Specialist",
    "marketing": "Marketing Specialist",
    "finance analyst": "Finance Analyst",
    "hr specialist": "HR Specialist",
    "human resources": "HR Specialist",
    "operations manager": "Operations Manager",
    "sales executive": "Sales Executive",
    "customer success manager": "Customer Success Manager",
    "cybersecurity analyst": "Cybersecurity Analyst",
    "security analyst": "Cybersecurity Analyst",
    "devops engineer": "DevOps Engineer",
    "devops": "DevOps Engineer",
    "business analyst": "Business Analyst",
    "project manager": "Project Manager",
    "research scientist": "Research Scientist",
    "content strategist": "Content Strategist",
    "teacher": "Teacher",
    "healthcare administrator": "Healthcare Administrator",
    "architect": "Architect",
    "consultant": "Other",
    "generalist": "Other",
}
